***@Author: Amar Pawar***
<br>

***@Date: 2021-07-12***
<br>

***@Last Modified by: Amar Pawar***
<br>

***@Last Modified time: 2021-07-12***
<br>

***@Title : Find real and imaginary parts of array of complex numbers***


In [1]:
import numpy as np

In [2]:
x = np.sqrt([1+0j])

In [3]:
y = np.sqrt([0+1j])

In [4]:
x.real

array([1.])

In [5]:
y.real

array([0.70710678])

In [6]:
x.imag

array([0.])

In [7]:
y.imag

array([0.70710678])